import os

QUEUE_URL = os.getenv('QUEUE_URL')
REGION_NAME = os.getenv('REGION_NAME')
S3_BUCKET = os.getenv('S3_BUCKET')

OPEN_SEARCH_HOST = os.getenv('OPEN_SEARCH_HOST')
OPEN_SEARCH_PASSWORD = os.getenv('OPEN_SEARCH_PASSWORD')
OPEN_SEARCH_USERNAME = os.getenv('OPEN_SEARCH_USERNAME')
OPEN_SEARCH_SECRET = os.getenv('OPEN_SEARCH_SECRET')

MYSQL_HOST = os.getenv('MYSQL_HOST')
MYSQL_USER = os.getenv('MYSQL_USER')
MYSQL_DATABASE = os.getenv('MYSQL_DATABASE')
MYSQL_SECRET = os.getenv('MYSQL_SECRET')


index_name = 'document_page'
